### PR TITLE
Detach branches on clone

### PR DESCRIPTION
**Pull request by mathomp4**
This PR should detach branches when doing clone steps.

Also adds `--detach` as an option to `checkout` commands because...why not?

### CODE REVIEW

**Comment by mathomp4** [comment]
@tclune I think this was something that was wanted right? Probably needs more testing, so I'm keeping draft, but I think it works...

**Review by tclune — APPROVED** [review]
Looks right.

**Comment by mathomp4** [comment]
I'll keep this draft until tomorrow. Finding a few fun bugs with `git checkout` and `--detach`. (NOTE: Bugs on my end)

**Comment by mathomp4** [comment]
Okay. I think I have this working. For a while there I broke backwards compatibility (by breaking `status` and `compare`) but I think I fixed it

**Pull request merged**
