### PR TITLE
Adds initial ability to see the fixture in mepo

### PR DESCRIPTION
**Pull request by mathomp4**
This is an attempt to get mepo to see the fixture repo as well as all the subrepos. To do so, additional changes are needed for the `components.yaml`. For example, for GEOSgcm:
```yaml
GEOSgcm:
   fixture: true
   develop: main
```
Only one of the entries in `components.yaml` is allowed to be a `fixture: True` and the only keys allowed for a fixture are `fixture:` and `develop:` since the actual `git clone` of the fixture is what provides the branch/tag.

### CODE REVIEW

**Comment by mathomp4** [comment]
Currently a draft PR as I want to be doubly sure this is still backward compatible.

**Comment by rtodling** [comment]
Hum,
I just added 

GEOSadas:
   fixture: true
   develop: main

tried doing a mepo status and still nothing changes ... I also tried using the mepo under your account:

/home/mathomp4/MepoDevelopment/mepo status

but still it doesn't seem to show my changes in the fixture.

I'm sure I am missing something from what you are doing.

Thx

**Comment by mathomp4** [comment]
@rtodling The version of `mepo` in my home directory on discover was not yet updated to this branch. I was doing local tests on my laptop for ease of testing (i.e., much faster disks). I have updated `~mathomp4/MepoDevelopment/mepo` to now be on the new branch.

Now, in order for `mepo` to see the fixture, `mepo` needs to be initialized with knowledge of the fixture (chicken and egg problem). But for testing, you can try the following:
```console
$ mkdir GEOSadas-with-mepo-fixture
$ cd GEOSadas-with-mepo-fixture
$ git clone -b feature/rtodling/migrate-to-geosadas5271  git@github.com:GEOS-ESM/GEOSadas.git 
$ cd GEOSadas
```
This gets just the fixture. Now, add:
```yaml
GEOSadas:
  fixture: true
  develop: main
```
to (the top of) `components.yaml`. Now if you run:
```console
$ /home/mathomp4/MepoDevelopment/mepo clone
Initializing mepo using components.yaml
env                    | (b) origin/feature/bmauer/updates-from-geosadas5_27_0
cmake                  | (t) v1.0.11
ecbuild                | (t) geos/v1.0.0
...
$ /home/mathomp4/MepoDevelopment/mepo status
Checking status...
GEOSadas               | (b) feature/rtodling/migrate-to-geosadas5271
   | components.yaml: modified, not staged
env                    | (b) feature/bmauer/updates-from-geosadas5_27_0 (DH)
cmake                  | (t) v1.0.11 (DH)
ecbuild                | (t) geos/v1.0.0 (DH)
...
```
You'll see that it now shows you have a modified file, `components.yaml`, in the fixture `GEOSadas`. 

As a test, I committed that change to a (temporary) branch of GEOSadas off of yours and then tried it all in one.

First, I will alias `mepo` to the development version for this just to cut down on extra text:
```console
$ alias mepo=/home/mathomp4/MepoDevelopment/mepo
$ source /home/mathomp4/MepoDevelopment/etc/mepo-cd.bash
```
Now let's clone my test branch from scratch:
```console
$ mkdir GEOSadas-with-mepo-fixture-in-repo
$ cd GEOSadas-with-mepo-fixture-in-repo
$ mepo clone -b feature/mathomp4/mepo-fixture-testing git@github.com:GEOS-ESM/GEOSadas.git
Initializing mepo using components.yaml
env                    | (b) origin/feature/bmauer/updates-from-geosadas5_27_0
cmake                  | (t) v1.0.11
ecbuild                | (t) geos/v1.0.0
...
$ cd GEOSadas
$ mepo status
Checking status...
GEOSadas               | (b) feature/mathomp4/mepo-fixture-testing
env                    | (b) feature/bmauer/updates-from-geosadas5_27_0 (DH)
cmake                  | (t) v1.0.11 (DH)
...
```
So the fixture is seen. Now we'll move up the tree, but do things in the fixture to make sure we are tracking it correctly:
```console
$ mepo-cd GEOSana_GridComp
$ pwd
/discover/swdev/mathomp4/Models/GEOSadas-with-mepo-fixture-in-repo/GEOSadas/src/Components/@GEOSana_GridComp
$ mepo whereis
GEOSadas               | ../../..
env                    | ../../../@env
cmake                  | ../../../@cmake
...
$ mepo checkout -b my-awesome-new-feature GEOSadas
+ GEOSadas: my-awesome-new-feature
$ mepo compare
Repo                   | Original                                            | Current
---------------------- | --------------------------------------------------- | -------
GEOSadas               | (b) feature/mathomp4/mepo-fixture-testing (DH)      | (b) my-awesome-new-feature
env                    | (b) feature/bmauer/updates-from-geosadas5_27_0 (DH) | (b) feature/bmauer/updates-from-geosadas5_27_0 (DH)
cmake                  | (t) v1.0.11 (DH)                                    | (t) v1.0.11 (DH)
...
$ /home/mathomp4/MepoDevelopment/mepo branch list GEOSadas
GEOSadas |   feature/mathomp4/mepo-fixture-testing
         | * my-awesome-new-feature
```
The new branch is seen, let's make a change:
```console
$ echo "This is a new line" >> $(mepo whereis GEOSadas)/README.md
$ mepo status
Checking status...
GEOSadas               | (b) my-awesome-new-feature
   | README.md: modified, not staged
env                    | (b) feature/bmauer/updates-from-geosadas5_27_0 (DH)
cmake                  | (t) v1.0.11 (DH)
...
$ mepo diff
Diffing...
GEOSadas (location: ../../..):

diff --git a/README.md b/README.md
index 3065294..792630d 100644
--- a/README.md
+++ b/README.md
@@ -188,3 +188,4 @@ cd install/bin
 ### Run the ADAS

 Like the AGCM step above, the ADAS setup scripts are also `install/bin/`
+This is a new line
$ mepo-cd
$ git status
On branch my-awesome-new-feature
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   README.md

no changes added to commit (use "git add" and/or "git commit -a")
```

NOTE 1: That the fixture monitoring of `mepo` only works with this (testing for now) version of `mepo`. You can't use an older `mepo` with it just because older `mepo` had some very strong restrictions that I had to relax in the case for fixtures. 

NOTE 2: I suggest putting the `GEOSadas:` bit at the top of `components.yaml` just because `mepo` initializes in the order of `components.yaml`. You could put it anywhere in the file, I just think the top is best.

If you could test this, that would be good. I am fairly certain with my testing that this new version is backward compatible (i.e., it works just fine with `components.yaml` without the `fixture` bits), but I want to consult with @tclune to make sure I get the SemVer right for a release. I am 99% certain it's a minor release ("MINOR version when you add functionality in a backwards compatible manner"), but I'd like his opinion.

**Review by bena-nasa — APPROVED** [review]

**Comment by mathomp4** [comment]
I am pulling this into a release just so I can do further work exploring it. All my tests show it to be backwards compatible.

**Pull request merged**
