### PR TITLE
Python package with expanded testing

### LINKED ISSUE #281: Poetry for packaging and dependency management
Consider poetry: https://python-poetry.org

### LINKED ISSUE #284: State file: pickle to json
Consider switching to `json` serialization format for storing the state from the current `pickle` format. This would ensure that issues like #279 don't come up again. A `json.dump` without indentation should reduce the risk of hand editing of the state file. 

For an older clone, made with `mepo 1`, a warning will be displayed, along with a solution of how to update to `mepo 2` style state
> Converting mepo1 state to mepo2 state
Run `mepo update-state` to permanently convert to mepo2 state

### PR DESCRIPTION
**Pull request by pchakraborty**
This PR addresses some of the concerns raised in #273 

- `mepo` is now a Python package with
    - `src/mepo/__init__.py`
    - `src/mepo/main.py` -> `src/mepo/__main__.py`. This allows one to execute `mepo` via `python -m mepo`. 

- `src/mepo/config/config_file.py` -> `src/mepo/registry.py`. So `components.yaml` is now called a registry, instead of a config file. While this change is mostly internal, it does affect the `clone` command - the optional argument `--config` to `mepo clone` is now `--registry`.

- More code reorganization
    - Using Python3's relative import
    - Code from `src/mepo/command/command.py` is now included in `__main__.py`
    - `src/mepo/command/<command>/<command>.py` -> `src/mepo/command/<command>.py`
        - subcommands are in files `src/command/<command_subcommand>.py`
    - `src/mepo/state/state.py` -> `src/mepo/state.py`
    - `src/mepo/state/component.py` -> `src/mepo/component.py`
    - `src/mepo/repository/git.py` -> `src/mepo/git.py`
    - Added optional argument `-1`/`--one-per-line` for `mepo list`

- Expanded testing to cover more `mepo` commands

- Since the `multiprocessing` library now supports the context manager protocol, we can write
  ```python
  import multiprocessing as mp
  with mp.Pool() as pool:
      result = pool.map(check_component_status, allcomps)
  ```
  3412ad75f418dee2a70a691e8be57f8af9952263, 376baf20dc9068236d98c703f5e71f7f60e85455
- Added linting via [Pylint](https://pylint.pycqa.org/en/latest/index.html)
- Implemented context manager for `os.chdir`. We can now do
  ```python
  from mepo.utilities import chdir as mepo_chdir
  with mepo_chdir(some_path):
      execute_some_command()
  ```
  instead of
  ```python
   import os
   cwd = os.getcwd()
   os.chdir(some_path)
   execute_some_command()
   os.chdir(cwd)
   ```
   Using `contextlib.chdir` when available (3.11+)
- Formatted code using [Black](https://black.readthedocs.io/en/stable/index.html)
- Managing project using [Poetry](https://python-poetry.org). Closes #281 
- Split GitHub actions workflow into three
   - Run mepo tests
   - Run formatter
   - Run linter
- Using `contextlib.redirect_stdout` to redirect stdout to variable
- Switched state file format from `pickle`d (*mepo1 style*) to `json` (*mepo2 style*). Closes #284 
   - If *mepo1 style* state is detected, print warning and suggest running `mepo update-state`
   - Added a new command `update-state` to permanently convert *mepo1 style* state to *mepo2 style*

### CODE REVIEW

**Comment by mathomp4** [comment]
@pchakraborty I think when I merged #279 that this became conflicted. Hopefully not too bad...but always scary when the web conflict resolver is greyed out...

**Comment by pchakraborty** [comment]
> @pchakraborty I think when I merged #279 that this became conflicted. Hopefully not too bad...but always scary when the web conflict resolver is greyed out...

@mathomp4 I've merged in the changes, but want to wait for a few days before merging in to develop. I've converted the pr to a draft one for the time being.

**Comment by pchakraborty** [comment]
@mathomp4 I think this is ready for merge. Converting to PR.

**Review by mathomp4 — APPROVED** [review]
Approve!

**Pull request merged**
